site_name: o2h.ch
sass:
  style: compressed
  sass_dir: _sass
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
collections:
  homepage_sections:
    sort_by: order
  photos:
    output: true
    permalink: /assets/photos/:name